### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#40]
I get the following error in my release build: 

```
10-11 03:06:28.766 1346-1357/? E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
10-11 03:06:28.766 1346-1357/? E/StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at dalvik.system.CloseGuard.open(CloseGuard.java:184)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:170)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:190)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1148)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at com.google.android.gms.googlehelp.search.a.a(SourceFile:55)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at com.google.android.gms.googlehelp.d.a.b(SourceFile:49)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at com.google.android.gms.googlehelp.search.a.e(SourceFile:113)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at com.google.android.gms.googlehelp.service.ClearHelpHistoryIntentService.onHandleIntent(SourceFile:49)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.os.Looper.loop(Looper.java:135)
10-11 03:06:28.766 1346-1357/? E/StrictMode:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by vals-productions** [comment]
Are you opening database multiple times?

**Comment by confile** [comment]
no only once.

**Comment by confile** [comment]
Do I have to close the database at some point? I did not find the close in your example.

**Comment by vals-productions** [comment]
My typical use case is to open the database and keep it open until the end, but yes, there should be the "close" method added. I'll add it.

**Comment by vals-productions** [comment]
But if you say you open the DB one time only, then this could be something else. Do you know how to reproduce it?

**Comment by confile** [comment]
I cannot reproduce it. Lets try with the close of the database first. Could you please add close to the android example so I can do it in my code too?

**Comment by vals-productions** [comment]
I've made the changes to android, ios and the demo. Try them. It feels to me that this could be an attempt to open DB connection second time without first closing it... or, an attempt to work with two databases with single SQLighter instance. For the latter it makes sense to use two distinct instances.

**Comment by confile** [comment]
Thank you

**Comment by confile** [comment]
let me check if the error still exist.

**Comment by vals-productions** [comment]
Closing the issue.
