### ISSUE TITLE
Android Demo Project Error

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#6]
The first time  I start the Android demo project I get the following error: 

```
09-18 17:08:14.663 3336-3336/com.prod.vals.andr_demo_prj D/dalvikvm: Late-enabling CheckJNI
09-18 17:08:14.903 3336-3336/com.prod.vals.andr_demo_prj I/dalvikvm: Could not find method android.view.ViewGroup.onRtlPropertiesChanged, referenced from method android.support.v7.widget.Toolbar.onRtlPropertiesChanged
09-18 17:08:14.903 3336-3336/com.prod.vals.andr_demo_prj W/dalvikvm: VFY: unable to resolve virtual method 13345: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
09-18 17:08:14.903 3336-3336/com.prod.vals.andr_demo_prj D/dalvikvm: VFY: replacing opcode 0x6f at 0x0007
09-18 17:08:14.913 3336-3336/com.prod.vals.andr_demo_prj I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
09-18 17:08:14.913 3336-3336/com.prod.vals.andr_demo_prj W/dalvikvm: VFY: unable to resolve virtual method 411: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
09-18 17:08:14.913 3336-3336/com.prod.vals.andr_demo_prj D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
09-18 17:08:14.913 3336-3336/com.prod.vals.andr_demo_prj I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
09-18 17:08:14.913 3336-3336/com.prod.vals.andr_demo_prj W/dalvikvm: VFY: unable to resolve virtual method 433: Landroid/content/res/TypedArray;.getType (I)I
09-18 17:08:14.913 3336-3336/com.prod.vals.andr_demo_prj D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
09-18 17:08:15.003 3336-3336/com.prod.vals.andr_demo_prj W/System.err: java.io.FileNotFoundException: /data/data/com.prod.vals.andr_demo_prj/databases/sqlite.sqlite: open failed: ENOENT (No such file or directory)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:416)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:128)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:117)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.vals.a2ios.sqlighter.impl.SQLighterDbImpl.copyDbOnce(SQLighterDbImpl.java:140)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.prod.vals.andr_demo_prj.MainActivity.onCreate(MainActivity.java:26)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.Activity.performCreate(Activity.java:5047)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.access$700(ActivityThread.java:134)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.os.Looper.loop(Looper.java:137)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4867)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at dalvik.system.NativeStart.main(Native Method)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err: Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at libcore.io.Posix.open(Native Method)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:400)
09-18 17:08:15.013 3336-3336/com.prod.vals.andr_demo_prj W/System.err:  ... 19 more
09-18 17:08:15.154 3336-3339/com.prod.vals.andr_demo_prj D/dalvikvm: GC_CONCURRENT freed 195K, 11% free 9533K/10695K, paused 19ms+2ms, total 94ms
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj E/SQLiteLog: (1) no such table: user
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err: android.database.sqlite.SQLiteException: no such table: user (code 1): , while compiling: select id, email, name, data, height from user
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1013)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:624)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.vals.a2ios.sqlighter.impl.SQLighterDbImpl.executeSelect(SQLighterDbImpl.java:179)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.prod.vals.andr_demo_prj.Demo.dbOperations(Demo.java:42)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.prod.vals.andr_demo_prj.MainActivity.onCreate(MainActivity.java:36)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.Activity.performCreate(Activity.java:5047)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.access$700(ActivityThread.java:134)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.os.Looper.loop(Looper.java:137)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4867)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
09-18 17:08:15.234 3336-3336/com.prod.vals.andr_demo_prj W/System.err:     at dalvik.system.NativeStart.main(Native Method)
09-18 17:08:15.304 3336-3336/com.prod.vals.andr_demo_prj D/libEGL: loaded /system/lib/egl/libEGL_mali.so
09-18 17:08:15.314 3336-3336/com.prod.vals.andr_demo_prj D/libEGL: loaded /system/lib/egl/libGLESv1_CM_mali.so
09-18 17:08:15.324 3336-3336/com.prod.vals.andr_demo_prj D/libEGL: loaded /system/lib/egl/libGLESv2_mali.so
09-18 17:08:15.474 3336-3336/com.prod.vals.andr_demo_prj D/OpenGLRenderer: Enabling debug mode 0
09-18 17:08:43.021 3336-3341/com.prod.vals.andr_demo_prj D/dalvikvm: Debugger has detached; object registry had 1 entries
```

On the second launch there is no error. Why is this so? Can I prevent this somehow?

**Comment by steffimueller** [comment]
@vals-productions I have the same problem. Why is this error occurring the first time?

**Comment by vals-productions** [comment]
So far I cannot reproduce. What do you guys mean by first time? I exit Android IDE, quit emulator, then start everything, no exception.

**Comment by confile** [comment]
Here is what I did. I opened the demo project for Android the first time and hit run. Then the error occurs. 

It seems that the database was not present the first time I launch the app. It seems to be created after that error occurs. 

Could you please describe how I do create the database if not present and check before if it is present?

**Comment by vals-productions** [comment]
I think it might be the case when the app is being first installed at the device. Will check that out.

**Comment by confile** [comment]
Yes that is the case. 

How do I check if the database has been generated?

**Comment by steffimueller** [comment]
Is there a way to check if the database does exist?

**Comment by vals-productions** [comment]
Guys, I found the fix. Will post shortly.

**Comment by vals-productions** [comment]
done

**Comment by confile** [comment]
How do I check if the database has been generated?

**Comment by vals-productions** [comment]
I added isDbFileDeployed

**Comment by confile** [comment]
How do I generate it if it is not deployed?

**Comment by vals-productions** [comment]
Generate what?

**Comment by confile** [comment]
Hot to generate the sql database if it does not exist?

**Comment by vals-productions** [comment]
It would help if you consult with sqlite documentation I think.
